# Generated by Django 6.1 on 2026-08-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
